python main.py \
--setting 1_2 \
--no-with_true_t_dens \
--no-calculate_con_dens \
--no-AdvRand \
--scale_dt \
--bn \
--lr_scheduler \
--early_stopping \
--dropout \
--simulate_new \
--verbose \
--noise 0.5 \
--n_layer_feat 1 \
--n_layer_head 1 \
--y_pow 4 \
--lr 1e-1 \
--n_repeats 10 \
--n_ensemble 10 \
--no-write_tensorboard