name: test_env
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - mysql-common=8.0.26
  - mysql-libs=8.0.26
  - numpy=1.20.2
  - numpy-base=1.20.2
  - pandas=1.2.5
  - pip=21.1.3
  - python=3.8.10
  - pytorch=1.10.0
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - pip:
    - py==1.11.0
    - ray==1.7.0
    - seaborn==0.11.2
    - tensorboard==2.6.0
    - tensorboardx==2.4
    - tensorflow==2.7.0
    - xgboost==1.5.0
    - rpy2==3.4.5
